
'use client'
import {useState,useEffect} from 'react'
import {FILMS as FALLBACK, GENRES} from '@/lib/films'
export default function BreakthroughAI(){
  const [films,setFilms]=useState<any[]>(FALLBACK)
  const [selected,setSelected]=useState<any>(null)
  const [genre,setGenre]=useState('All')
  useEffect(()=>{fetch('/api/films').then(r=>r.json()).then(d=>{if(Array.isArray(d)&&d.length>0){const now=new Date(); const live=d.filter((f:any)=>!f.scheduled_release_at||new Date(f.scheduled_release_at)<=now); setFilms(live.length>0?live:d)}})},[])
  const filtered=genre==='All'?films:films.filter(f=>f.genre===genre)
  const featured=films.filter(f=>f.status==='featured')
  const checkout=async()=>{const r=await fetch('/api/stripe/checkout',{method:'POST'});const d=await r.json();if(d.url) location.href=d.url;else alert(d.error)}
  return <main style={{background:'#050505',color:'#fff',minHeight:'100vh'}}>
    <header style={{position:'fixed',top:0,width:'100%',zIndex:50,display:'flex',justifyContent:'space-between',padding:'14px 24px',background:'rgba(5,5,5,0.96)',borderBottom:'1px solid rgba(255,255,255,0.08)',backdropFilter:'blur(20px)'}}>
      <div style={{display:'flex',gap:14,alignItems:'center'}}><div style={{width:38,height:38,background:'#E50914',borderRadius:12,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:20,letterSpacing:'-0.05em'}}>B</div><div><div style={{fontWeight:900,fontSize:18,letterSpacing:'-0.02em',lineHeight:1}}>BREAKTHROUGH.AI</div><div style={{fontSize:9,letterSpacing:'0.2em',color:'rgba(255,255,255,0.5)',fontWeight:700}}>EVERY FILM WAS NEVER FILMED</div></div><span style={{fontSize:9,background:'#22c55e',color:'#000',padding:'4px 8px',borderRadius:999,fontWeight:900,marginLeft:12}}>● AI BOT RUNNING</span></div>
      <div style={{display:'flex',gap:8,alignItems:'center'}}><a href="/bot" style={{background:'#22c55e',color:'#000',padding:'10px 18px',borderRadius:999,fontWeight:900,fontSize:12,textDecoration:'none'}}>🤖 Bot Runs Site</a><a href="/studio" style={{background:'#1a1a1a',color:'#fff',padding:'10px 18px',borderRadius:999,fontWeight:800,fontSize:12,textDecoration:'none',border:'1px solid rgba(255,255,255,0.1)'}}>Studio</a><button onClick={checkout} style={{background:'#fff',color:'#000',border:'none',padding:'10px 18px',borderRadius:999,fontWeight:900,fontSize:12,cursor:'pointer'}}>Go Pro $9.99 →</button></div>
    </header>
    <section style={{padding:'90px 24px 20px',maxWidth:1680,margin:'0 auto'}}>
      <div style={{background:'radial-gradient(140% 120% at 0% 0%, #111827 0%, #000 70%)',borderRadius:28,padding:'48px 40px',border:'1px solid rgba(255,255,255,0.08)',position:'relative',overflow:'hidden'}}>
        <div style={{position:'absolute',inset:0,background:'radial-gradient(600px 600px at 80% 20%, rgba(229,9,20,0.12), transparent)'}}/>
        <div style={{position:'relative'}}>
          <div style={{display:'inline-flex',gap:8,alignItems:'center',background:'rgba(229,9,20,0.1)',border:'1px solid rgba(229,9,20,0.2)',padding:'6px 12px',borderRadius:999,fontSize:10,letterSpacing:'0.2em',fontWeight:900,color:'#E50914'}}>● BREAKTHROUGH.AI • LIVE AI GENERATOR • STRATEGIC RELEASES • DOMAIN: BREAKTHROUGH.AI</div>
          <h1 style={{fontSize:'clamp(42px,8vw,96px)',fontWeight:900,lineHeight:0.85,margin:'20px 0 0',letterSpacing:'-0.04em'}}>Every film<br/>was never<br/><span style={{color:'#E50914'}}>filmed.</span></h1>
          <p style={{color:'rgba(255,255,255,0.55)',maxWidth:680,marginTop:20,fontSize:15,lineHeight:1.6}}>Breakthrough.ai is real AI streaming. AI showrunner bot runs whole site 1am daily — analyzes catalog, plans strategic weekly releases (Mon Drama, Tue Thriller...), generates max 3/day staggered 2h/6h/10h, auto-removes flops after 14 days, features hits 30 days. Not flooding. Organized like Netflix.</p>
          <div style={{display:'flex',gap:12,marginTop:28,flexWrap:'wrap'}}><a href="/bot" style={{background:'#fff',color:'#000',padding:'14px 26px',borderRadius:999,fontWeight:900,textDecoration:'none',fontSize:14}}>🤖 See Bot Strategy — Runs Whole Site</a><button onClick={()=>fetch('/api/bot/run').then(r=>r.json()).then(d=>alert(d.summary))} style={{background:'#22c55e',color:'#000',border:'none',padding:'14px 26px',borderRadius:999,fontWeight:900,cursor:'pointer',fontSize:14}}>Run Breakthrough Bot Now</button></div>
          <div style={{marginTop:20,fontSize:11,fontFamily:'monospace',color:'rgba(255,255,255,0.35)'}}>breakthrough.ai • /api/bot/run 1am • /api/cron/cleanup 3am • /api/cron/feature every 6h • AI bot organized • Not non-stop generator</div>
        </div>
      </div>
    </section>
    {featured.length>0&&<section style={{maxWidth:1680,margin:'0 auto',padding:'0 24px 16px'}}><h2 style={{fontSize:12,fontWeight:900,letterSpacing:'0.14em'}}>★ FEATURED LONGEST ON BREAKTHROUGH.AI • Most Popular Stay 30 Days</h2><div style={{display:'flex',gap:14,overflowX:'auto',paddingTop:12}}>{featured.slice(0,6).map(f=><div key={f.id} onClick={()=>setSelected(f)} style={{minWidth:300,background:'#111',borderRadius:16,overflow:'hidden',border:'1px solid #facc15',cursor:'pointer'}}><video src={f.video_url} muted style={{width:'100%',height:170,objectFit:'cover'}}/><div style={{padding:14}}><div style={{fontWeight:900,fontSize:13}}>{f.title}</div><div style={{fontSize:11,color:'#facc15',marginTop:4}}>★ {f.views} views • Breakthrough featured longest</div></div></div>)}</div></section>}
    <div style={{maxWidth:1680,margin:'0 auto',padding:'0 24px',display:'flex',gap:8,overflowX:'auto'}}>{GENRES.map(g=><button key={g} onClick={()=>setGenre(g)} style={{background:genre===g?'#fff':'rgba(255,255,255,0.06)',color:genre===g?'#000':'#fff',border:'none',padding:'8px 18px',borderRadius:999,fontSize:12,fontWeight:800,cursor:'pointer',whiteSpace:'nowrap'}}>{g}</button>)}</div>
    <section style={{maxWidth:1680,margin:'0 auto',padding:20}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(250px,1fr))',gap:16}}>{filtered.map(f=><div key={f.id} onClick={()=>setSelected(f)} style={{background:'#0f0f0f',borderRadius:16,overflow:'hidden',border:f.status==='featured'?'1px solid #facc15':'1px solid rgba(255,255,255,0.06)',cursor:'pointer'}}><video src={f.video_url} muted style={{width:'100%',height:320,objectFit:'cover'}}/><div style={{padding:14}}><div style={{fontWeight:800,fontSize:13}}>{f.title}</div><div style={{fontSize:10,color:'rgba(255,255,255,0.5)',marginTop:4}}>{f.genre} • {f.views} views • {f.status} • breakthrough.ai</div></div></div>)}</div></section>
    {selected&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.94)',zIndex:100,display:'flex',justifyContent:'center',alignItems:'center',padding:20}} onClick={()=>setSelected(null)}><div style={{background:'#0a0a0a',borderRadius:24,maxWidth:1100,width:'100%',overflow:'hidden',border:'1px solid rgba(255,255,255,0.08)'}} onClick={e=>e.stopPropagation()}><video src={selected.video_url} controls autoPlay style={{width:'100%',aspectRatio:'16/9'}}/><div style={{padding:20}}><div style={{fontWeight:900,fontSize:20}}>BREAKTHROUGH.AI • {selected.title}</div><div style={{fontSize:13,color:'rgba(255,255,255,0.6)',marginTop:8}}>{selected.synopsis}</div></div></div></div>}
  </main>
}
