export const FILMS=[
  {
    "id": "bt-0",
    "title": "BREAKTHROUGH FILM 1",
    "genre": "Drama",
    "synopsis": "Breakthrough AI generated film 1 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5000,
    "likes": 0,
    "featured_score": 0,
    "status": "featured"
  },
  {
    "id": "bt-1",
    "title": "BREAKTHROUGH FILM 2",
    "genre": "Thriller",
    "synopsis": "Breakthrough AI generated film 2 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5120,
    "likes": 3,
    "featured_score": 10,
    "status": "featured"
  },
  {
    "id": "bt-2",
    "title": "BREAKTHROUGH FILM 3",
    "genre": "Sci-Fi",
    "synopsis": "Breakthrough AI generated film 3 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5240,
    "likes": 6,
    "featured_score": 20,
    "status": "featured"
  },
  {
    "id": "bt-3",
    "title": "BREAKTHROUGH FILM 4",
    "genre": "Romance",
    "synopsis": "Breakthrough AI generated film 4 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5360,
    "likes": 9,
    "featured_score": 30,
    "status": "featured"
  },
  {
    "id": "bt-4",
    "title": "BREAKTHROUGH FILM 5",
    "genre": "Horror",
    "synopsis": "Breakthrough AI generated film 5 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5480,
    "likes": 12,
    "featured_score": 40,
    "status": "featured"
  },
  {
    "id": "bt-5",
    "title": "BREAKTHROUGH FILM 6",
    "genre": "Drama",
    "synopsis": "Breakthrough AI generated film 6 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5600,
    "likes": 15,
    "featured_score": 50,
    "status": "featured"
  },
  {
    "id": "bt-6",
    "title": "BREAKTHROUGH FILM 7",
    "genre": "Thriller",
    "synopsis": "Breakthrough AI generated film 7 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5720,
    "likes": 18,
    "featured_score": 60,
    "status": "live"
  },
  {
    "id": "bt-7",
    "title": "BREAKTHROUGH FILM 8",
    "genre": "Sci-Fi",
    "synopsis": "Breakthrough AI generated film 8 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5840,
    "likes": 21,
    "featured_score": 70,
    "status": "live"
  },
  {
    "id": "bt-8",
    "title": "BREAKTHROUGH FILM 9",
    "genre": "Romance",
    "synopsis": "Breakthrough AI generated film 9 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 5960,
    "likes": 24,
    "featured_score": 80,
    "status": "live"
  },
  {
    "id": "bt-9",
    "title": "BREAKTHROUGH FILM 10",
    "genre": "Horror",
    "synopsis": "Breakthrough AI generated film 10 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6080,
    "likes": 27,
    "featured_score": 90,
    "status": "live"
  },
  {
    "id": "bt-10",
    "title": "BREAKTHROUGH FILM 11",
    "genre": "Drama",
    "synopsis": "Breakthrough AI generated film 11 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6200,
    "likes": 30,
    "featured_score": 100,
    "status": "live"
  },
  {
    "id": "bt-11",
    "title": "BREAKTHROUGH FILM 12",
    "genre": "Thriller",
    "synopsis": "Breakthrough AI generated film 12 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6320,
    "likes": 33,
    "featured_score": 110,
    "status": "live"
  },
  {
    "id": "bt-12",
    "title": "BREAKTHROUGH FILM 13",
    "genre": "Sci-Fi",
    "synopsis": "Breakthrough AI generated film 13 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6440,
    "likes": 36,
    "featured_score": 120,
    "status": "live"
  },
  {
    "id": "bt-13",
    "title": "BREAKTHROUGH FILM 14",
    "genre": "Romance",
    "synopsis": "Breakthrough AI generated film 14 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6560,
    "likes": 39,
    "featured_score": 130,
    "status": "live"
  },
  {
    "id": "bt-14",
    "title": "BREAKTHROUGH FILM 15",
    "genre": "Horror",
    "synopsis": "Breakthrough AI generated film 15 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6680,
    "likes": 42,
    "featured_score": 140,
    "status": "live"
  },
  {
    "id": "bt-15",
    "title": "BREAKTHROUGH FILM 16",
    "genre": "Drama",
    "synopsis": "Breakthrough AI generated film 16 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6800,
    "likes": 45,
    "featured_score": 150,
    "status": "live"
  },
  {
    "id": "bt-16",
    "title": "BREAKTHROUGH FILM 17",
    "genre": "Thriller",
    "synopsis": "Breakthrough AI generated film 17 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 6920,
    "likes": 48,
    "featured_score": 160,
    "status": "live"
  },
  {
    "id": "bt-17",
    "title": "BREAKTHROUGH FILM 18",
    "genre": "Sci-Fi",
    "synopsis": "Breakthrough AI generated film 18 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 7040,
    "likes": 51,
    "featured_score": 170,
    "status": "live"
  },
  {
    "id": "bt-18",
    "title": "BREAKTHROUGH FILM 19",
    "genre": "Romance",
    "synopsis": "Breakthrough AI generated film 19 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 7160,
    "likes": 54,
    "featured_score": 180,
    "status": "live"
  },
  {
    "id": "bt-19",
    "title": "BREAKTHROUGH FILM 20",
    "genre": "Horror",
    "synopsis": "Breakthrough AI generated film 20 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 7280,
    "likes": 57,
    "featured_score": 190,
    "status": "live"
  },
  {
    "id": "bt-20",
    "title": "BREAKTHROUGH FILM 21",
    "genre": "Drama",
    "synopsis": "Breakthrough AI generated film 21 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 7400,
    "likes": 60,
    "featured_score": 200,
    "status": "live"
  },
  {
    "id": "bt-21",
    "title": "BREAKTHROUGH FILM 22",
    "genre": "Thriller",
    "synopsis": "Breakthrough AI generated film 22 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "match": 85,
    "duration": "0m 12s",
    "year": "2025",
    "views": 7520,
    "likes": 63,
    "featured_score": 210,
    "status": "live"
  },
  {
    "id": "bt-22",
    "title": "BREAKTHROUGH FILM 23",
    "genre": "Sci-Fi",
    "synopsis": "Breakthrough AI generated film 23 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "match": 86,
    "duration": "0m 12s",
    "year": "2025",
    "views": 7640,
    "likes": 66,
    "featured_score": 220,
    "status": "live"
  },
  {
    "id": "bt-23",
    "title": "BREAKTHROUGH FILM 24",
    "genre": "Romance",
    "synopsis": "Breakthrough AI generated film 24 - every film was never filmed, generated live by AI bot",
    "video_url": "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "match": 87,
    "duration": "0m 12s",
    "year": "2025",
    "views": 7760,
    "likes": 69,
    "featured_score": 230,
    "status": "live"
  }
]
export const GENRES=['All','Drama','Horror','Thriller','Sci-Fi','Romance','Dark Comedy','True Crime AI']
