'use client'
import { Suspense, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { createBrowserClient } from '@supabase/ssr'

const supabase = createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!)

function LoginForm(){
  const searchParams=useSearchParams(); const next=searchParams.get('next')||'/'; const safeNext=next.startsWith('/')&&!next.startsWith('//')?next:'/'
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [phone,setPhone]=useState(''); const [otp,setOtp]=useState(''); const [phoneStep,setPhoneStep]=useState(false); const [msg,setMsg]=useState(searchParams.get('error')==='oauth'?'Sign-in could not be completed. Please try again.':''); const [loading,setLoading]=useState(false); const [oauthLoading,setOauthLoading]=useState(''); const [phoneLoading,setPhoneLoading]=useState(false)
  async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMsg('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.trim(),password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to log in.');location.href=safeNext}catch(e){setMsg(e instanceof Error?e.message:'Unable to log in.');setLoading(false)}}
  async function signInWithProvider(provider:'google'|'apple'){setOauthLoading(provider);setMsg('');const redirectTo=`${window.location.origin}/auth/callback?next=${encodeURIComponent(safeNext)}`;const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo}});if(error){setMsg(error.message);setOauthLoading('')}}
  async function sendPhoneCode(e:React.FormEvent){e.preventDefault();setPhoneLoading(true);setMsg('');const {error}=await supabase.auth.signInWithOtp({phone:phone.trim(),options:{shouldCreateUser:false}});if(error){setMsg(error.message);setPhoneLoading(false);return}setPhoneStep(true);setMsg('Verification code sent.');setPhoneLoading(false)}
  async function verifyPhone(e:React.FormEvent){e.preventDefault();setPhoneLoading(true);setMsg('');const {error}=await supabase.auth.verifyOtp({phone:phone.trim(),token:otp.trim(),type:'sms'});if(error){setMsg(error.message);setPhoneLoading(false);return}location.href=safeNext}
  const disabled=loading||!!oauthLoading||phoneLoading
  return <section className="formPage"><div className="eyebrow">Welcome back</div><h1>Log in</h1><button className="btn" type="button" onClick={()=>signInWithProvider('google')} disabled={disabled}>{oauthLoading==='google'?'Connecting…':'Continue with Google'}</button><button className="btn" type="button" onClick={()=>signInWithProvider('apple')} disabled={disabled} style={{marginTop:10}}>{oauthLoading==='apple'?'Connecting…':'Continue with Apple'}</button><div style={{display:'flex',alignItems:'center',gap:12,margin:'18px 0',color:'rgba(255,255,255,.45)',fontSize:12}}><span style={{height:1,flex:1,background:'rgba(255,255,255,.14)'}}/><span>OR</span><span style={{height:1,flex:1,background:'rgba(255,255,255,.14)'}}/></div>{!phoneStep?<form onSubmit={sendPhoneCode}><input className="input" placeholder="Phone number (+1 555 123 4567)" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} required autoComplete="tel"/><button className="btn" type="submit" disabled={disabled}>{phoneLoading?'Sending code…':'Continue with phone'}</button></form>:<form onSubmit={verifyPhone}><input className="input" placeholder="6-digit verification code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} required autoComplete="one-time-code"/><button className="btn primary" type="submit" disabled={disabled}>{phoneLoading?'Verifying…':'Verify & continue'}</button><button className="btn" type="button" onClick={()=>{setPhoneStep(false);setOtp('');setMsg('')}} disabled={phoneLoading} style={{marginTop:10}}>Use a different number</button></form>}<div style={{display:'flex',alignItems:'center',gap:12,margin:'18px 0',color:'rgba(255,255,255,.45)',fontSize:12}}><span style={{height:1,flex:1,background:'rgba(255,255,255,.14)'}}/><span>OR</span><span style={{height:1,flex:1,background:'rgba(255,255,255,.14)'}}/></div><form onSubmit={submit}><input className="input" placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/><input className="input" placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/><button className="btn primary" type="submit" disabled={disabled}>{loading?'Signing in…':'Log in'}</button></form>{msg&&<div className="notice" style={{color:msg.toLowerCase().includes('sent')?'#c7f9d4':'#ffb4b4'}}>{msg}</div>}<p className="muted">New here? <a href="/signup">Create an account</a></p></section>
}

export default function Login(){return <main className="shell"><nav className="nav"><a className="brand" href="/">BREAKTHROUGH</a></nav><Suspense fallback={<section className="formPage"><div className="eyebrow">Welcome back</div><h1>Log in</h1></section>}><LoginForm/></Suspense></main>}
